import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  titleContainer: {
    alignItems: 'center',
    marginBottom: 50,
  },
  mainTitle: {
    fontFamily: 'Monsterrat',
    fontWeight: "bold",
    fontStyle: "italic",
    fontSize: 60,
    color: 'white',
    textAlign: 'center',
  },
  descriptionTitle: {
    fontFamily: 'Monsterrat',
    fontStyle: "italic",
    fontSize: 20,
    color: 'white',
  },
  buttonsContainer: {
    width: '80%',
    alignItems: 'center',
  },
  mainMenuButton: {
    width: 180,
    height: 70,
    backgroundColor: '#D7DCEA',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  button: {
    width: 180,
    height: 70,
    backgroundColor: '#D7DCEA',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginVertical: 10,
    alignSelf: 'center',
  },
  buttonText: {
    color: '#6581BF',
    fontSize: 20,
    textAlign: 'center',
    fontFamily: 'Monsterrat',
    fontWeight: 'bold',
  },
  iconContainer: {
    width: 22,
    alignItems: "center",
    justifyContent: 'center',
    marginRight: 5,
  },
  input: {
    width: '90%',
    height: 50,
    backgroundColor: '#D7DCEA',
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 15,
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: 'Monsterrat',
  },
  searchBar: {
    backgroundColor: '#D7DCEA',
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
    fontSize: 18,
    color: '#666',
    width: "90%",
    alignSelf: "center",
  },
  locationBox: {
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D7DCEA',
    borderRadius: 30,
    padding: 2.5,
    marginVertical: 10,
  },
  locationButton: {
    backgroundColor: '#A1B3D7',
    borderRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignItems: 'center',
    flexDirection: 'row',
  },
  locationText: {
    fontSize: 16,
    fontFamily: 'Monsterrat',
    color: '#000',
    includeFontPadding: false,
  },
  cameraBox: {
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D7DCEA',
    borderRadius: 30,
    padding: 2.5,
    marginVertical: 10,
  },
  cameraButton: {
    backgroundColor: '#A1B3D7',
    borderRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignItems: 'center',
    flexDirection: 'row',
  },
  cameraText: {
    fontSize: 16,
    fontFamily: 'Monsterrat',
    color: '#000',
    includeFontPadding: false,
  },
  imageContainer: {
    width: '90%',
    marginVertical: 10,
    aspectRatio: 16 / 9,
    backgroundColor: '#A1B3D7',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    overflow: 'hidden',
  },
  image: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
    resizeMode: 'contain',
  },
  emptyText: {
    fontFamily: 'Monsterrat',
    fontSize: 18,
    color: 'white',
    textAlign: 'center',
    marginTop: 20,
  },
  itemCard: {
    backgroundColor: '#D7DCEA',
    padding: 15,
    marginBottom: 10,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    width: '90%',
  },
  itemName: {
    fontFamily: 'Monsterrat',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#6581BF',
    flex: 1,
  },
  itemImage: {
    width: 60,
    height: 60,
    borderRadius: 10,
    marginLeft: 10,
  },
  content: {
    alignItems: 'center',
    width: '100%',
  },
  title: {
    fontSize: 36,
    fontWeight: 'bold',
    fontStyle: 'italic',
    color: 'white',
    textAlign: 'center',
    marginBottom: 15,
  },
  description: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
    marginBottom: 20,
  },
  gpsText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#6581BF',
    textAlign: 'center',
  },
  inputField: {
    backgroundColor: '#D7DCEA',
    padding: 10,
    borderRadius: 10,
    width: "100%",
    color: '#000',
  },
  takePictureButton: {
    backgroundColor: '#6581BF',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 30,
  },
  takePictureText: {
    color: 'white',
    fontSize: 18,
    marginLeft: 10,
    fontWeight: 'bold',
  },
  gpsBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D7DCEA',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 50,
    marginBottom: 20,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 20,
  },
  deleteButton: {
    backgroundColor: '#FF6B6B',
    width: 180,
    height: 70,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginVertical: 10,
  },
  deleteButtonText: {
    color: '#000',
    fontSize: 20,
    textAlign: 'center',
    fontWeight: 'bold',
  },
});

export default styles;